version: '3.9'
services:

  wordpress:
    image: wordpress:php7.4-fpm-custom
    container_name: wp-wordpress
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - mariadb
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_PHP_CONFIG}:/usr/local/etc/php/conf.d
      - ${WORDPRESS_FPM_CONFIG}:/usr/local/etc/php-fpm.d
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  mariadb:
    image: mariadb:11.5
    container_name: wp-mariadb
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--skip-character-set-client-handshake"
    ]
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql

  nginx:
    image: nginx:1
    container_name: wp-nginx
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "8080:80"    # http
      - "8443:443"   # https
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d
      - ${NGINX_SSL_CERTS}:/etc/ssl
      - ${NGINX_LOGS}:/var/log/nginx

  redis:
    image: redis:7.2.4-custom
    container_name: wp-redis
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.redis
      args:
        REDIS_PASSWORD: "${REDIS_ROOT_PASSWORD}"
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_LOCAL_HOME}:/root/redis
      - ${REDIS_CONFIG}:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: "${REDIS_ROOT_PASSWORD}"
      # REDIS_PORT: 6379
    networks:
      - wordpress


  phpmyadmin:
    image: phpmyadmin:latest  # https://hub.docker.com/_/phpmyadmin
    container_name: wp-phpmyadmin
    env_file:
      - .env
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      # MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 250M
    ports:
      - 0.0.0.0:8085:80
    links:
      - mariadb:mariadb
    volumes:
     - ${PHP_MY_ADMIN_PHP_CONF}:/usr/local/etc/php/conf.d/conf.ini
     - ${PHP_MY_ADMIN_PMA_CONF}:/etc/phpmyadmin/config.user.inc.php
    networks:
      - wordpress


networks:
  wordpress:
    name: wp-wordpress
    driver: bridge