version: '3.9'
services:

  wordpress:
    image: wordpress:php7.4-fpm-custom
    container_name: wp-wordpress
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  mariadb:
    image: mariadb:11.5
    container_name: wp-mariadb
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--skip-character-set-client-handshake"
    ]
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: wp-nginx
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "8080:80"    # http
      - "8443:443"   # https
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

  redis:
    image: redis:7.2.4-custom
    container_name: wp-redis
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.redis
      args:
        REDIS_PASSWORD: "${REDIS_ROOT_PASSWORD}"
    ports:
      - ${IP}:6379:6379
    volumes:
      - redis_data:/root/redis
      - redis_config:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: "${REDIS_ROOT_PASSWORD}"
      # REDIS_PORT: 6379
    networks:
      - wordpress


  phpmyadmin:
    image: phpmyadmin:latest  # https://hub.docker.com/_/phpmyadmin
    container_name: wp-phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: mariadb
      PMA_PORT: 3306
      # MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 250M
    ports:
      - 0.0.0.0:8080:80
    links:
      - db:db
    volumes:
     - ./config/pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
     - ./config/pma_config.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - wordpress


networks:
  wordpress:
    name: wp-wordpress
    driver: bridge